# Generated by Django 5.0.4 on 2024-06-03 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='topic',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
