# Generated by Django 5.0.4 on 2024-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_topic_alter_postmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
