# Generated by Django 5.0.4 on 2024-06-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postmodel_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='topic',
        ),
    ]
